services:
  app:
    environment:
      PHP_OPCACHE_ENABLE: "false"
      APP_ENV: "test"
    ports:
      - "8080"
  mariadb:
    # Functional tests will need working database
    ports:
     - "3306"