doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: 'mariadb-10.6.0'
        charset: 'utf8mb4'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Account:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Account/Infrastructure/Doctrine/Entity'
                prefix: 'App\Account\Infrastructure\Doctrine\Entity'
                alias: Account
            Game:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Game/Infrastructure/Doctrine/Entity'
                prefix: 'App\Game\Infrastructure\Doctrine\Entity'
                alias: Game

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
